### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [mtkbaby/prj-rev-bwfs-dasmoto#6]
https://github.com/mtkbaby/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L9-L22

There is a lot of repetition occurring in these rules and there are opportunities for refactoring. Try to extract the common styles into a single rule with a more general selector, for example:

```css
h2 {
  color: white;
  font-weight:bold;
  font-size: 32px
}

#frames {
  background-color: lightcoral;
}
```
